---
title: "assignment5"
author: "hongsheng zhang"
date: '2022-12-01'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
rm(list=ls())
setwd("~/Desktop/2022-2023 Fall term/Stat 353/Assignments")
knitr::opts_chunk$set(echo = TRUE)

data1 <- read.csv(file = "data-table-B4.csv")
```
# Q2
```{r}

x<-c(100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300)
y<-c(9.73, 9.61, 8.15, 6.98, 5.87, 4.98, 5.09, 4.79, 4.02, 4.46, 3.82)

x2=pmax(x-200,0)^0
x3=pmax(x-200,0)^1

l=lm(y~x+x2+x3)
r=l$residuals
fit=y-r
plot(fit,r)

l2=lm(y~x+x3)
r2=l2$residuals
fit2=y-r2
plot(fit2,r2)

qqnorm(r)
qqline(r)
qqnorm(r2)
qqline(r2)



summary(l)

```

#Q3(a)

```{r}

attach(data1)
(n=length(y))

model1=lm(y~., data=data1)
step1=step(model1, scope=list(upper=~x1+x2+x3+x4+x5+x6+x7+x8+x9, lower=~1))
summary(step1)

```
#Q3(b)
```{r}
x1 = data1[,2]
x2 = data1[,3]
x5 = data1[,6]
x7 = data1[,8]
M1=lm(y~x1+x2+x5+x7)
resid=M1$residuals
fit=y-resid

plot(fit,resid, main="Model: y~x1+x2+x5+x7")
abline(h=0)
qqnorm(resid)
qqline(resid)
shapiro.test(resid)
summary(M1)
```
